language: php

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0
  fast_finish: true

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpcs
  - vendor/bin/php-cs-fixer fix --config-file=.php_cs --verbose --diff --dry-run
  - vendor/bin/phpunit
