symlink-sdk:
	mkdir -p vendor/saritasa
	rm -rf vendor/saritasa/opbeat-laravel
	cd vendor/saritasa && ln -sf ../../../.. opbeat-laravel

	rm -rf vendor/sentry/opbeat
	cd vendor/saritasa && ln -sf ../../../../../opbeat-php opbeat
